package com.commonutilities.enumsutility;

public enum propertkeys 
{
AUSERNAME,APASSWORD,TUSERNAME,TPASSWORD,PUSERNAME,PPASSWORD,BROWSER,TIMEOUT,USERNAME,PASSWORD,URL,EXTENTREPORTTITLE,EXTENTREPORTNAME,
 OVERRIDEREPORT,
}
